version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet      # 潜在的なバグ検出
    - errcheck   # エラーハンドリングチェック
    - staticcheck # 静的解析（gosimple, unusedを含む）
    - ineffassign # 無駄な代入検出

formatters:
  enable:
    - gofmt      # コードフォーマットチェック
    - goimports  # import文の整理

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
